name: smart_watch_widget
description: A smart watch widget for windows.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  analog_clock: #^0.1.0
    git: 
      url: https://github.com/YehudaKremer/analog_clock.git
      ref: fix-digital-clock-live
  flutter_acrylic: ^1.0.0+1
  bitsdojo_window: ^0.1.1+1
  provider: ^6.0.2
  fluent_ui: ^3.9.1
  fluentui_system_icons: ^1.1.161
  system_theme: ^1.0.1
  window_manager: ^0.1.9
  shared_preferences: ^2.0.13
  intl: ^0.17.0
  hotkey_manager: ^0.1.6
  libmpv:
    git:
      url: https://github.com/harmonoid/libmpv.dart.git
  new_im_animations: ^0.1.1
  schedulers: ^0.3.1
  win_toast: ^0.0.2
  flutter_colorpicker: ^1.0.3
  hexcolor: ^2.0.6
  wave: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/audio/Twin-bell-alarm-clock.mp3

msix_config:
  display_name: Smart Watch Widget
  publisher_display_name: Kremer Software
  identity_name: 48434KremerSoftware.SmartWatchWidget
  publisher: CN=BF257F3F-5644-46DF-8668-014044C1B138
  msix_version: 1.0.0.0
  logo_path: images\logo-light.png
  enable_at_startup : true
  store: true
