name: smart_watch_widget
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  analog_clock: ^0.1.0
  flutter_acrylic: ^1.0.0+1
  bitsdojo_window: ^0.1.1+1
  provider: ^6.0.2
  fluent_ui: ^3.9.1
  fluentui_system_icons: ^1.1.161
  system_theme: ^1.0.1
  window_manager: ^0.1.9
  shared_preferences: ^2.0.13
  intl: ^0.17.0
  hotkey_manager: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.3.1

flutter:
  uses-material-design: true
