# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          body: ""
          tag_name: "vnext"
          files: |
            build/windows/runner/Release/smart_watch_widget.exe
